CREATE TABLE USERS (
    USERID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USERNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE MAPS (
    MAPID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    BANNER VARCHAR NOT NULL,
    MAP JSONB NOT NULL,
    NAME VARCHAR(100) NOT NULL
);
CREATE TABLE USERSPACES (
    SPACEID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USERID UUID NOT NULL,
    SPACENAME VARCHAR(100) NOT NULL,
    MAPID UUID NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USERID) REFERENCES USERS(USERID),
    FOREIGN KEY (MAPID) REFERENCES MAPS(MAPID),
    UNIQUE (USERID, SPACENAME)
);
CREATE TABLE ROOMUSERS (
    ROOMID UUID NOT NULL,
    USERID UUID NOT NULL,
    X INTEGER NOT NULL,
    Y INTEGER NOT NULL,
    PRIMARY KEY (ROOMID, USERID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);
